- task: PowerShell@2
  enabled: true
  displayName: "Install dependencies"
  inputs:
    targetType: "inline"
    script: "npm ci"
    workingDirectory: path/to/playwright/folder # update accordingly

- task: PowerShell@2
  enabled: true
  displayName: "Run Playwright tests"
  env:
    PLAYWRIGHT_SERVICE_ACCESS_TOKEN: $(PLAYWRIGHT_SERVICE_ACCESS_TOKEN)
    PLAYWRIGHT_SERVICE_URL: $(PLAYWRIGHT_SERVICE_URL)
  inputs:
    targetType: "inline"
    script: "npx playwright test -c playwright.service.config.ts --workers=20"
    workingDirectory: path/to/playwright/folder # update accordingly

- task: PublishPipelineArtifact@1
  displayName: Upload Playwright report
  inputs:
    targetPath: path/to/playwright/folder/playwright-report/ # update accordingly
    artifact: "Playwright tests"
    publishLocation: "pipeline"
- task: PowerShell@2
  enabled: true
  displayName: "Install dependencies"
  inputs:
    targetType: "inline"
    script: "npm ci"
    workingDirectory: path/to/playwright/folder # update accordingly

- task: PowerShell@2
  enabled: true
  displayName: "Run Playwright tests"
  env:
    PLAYWRIGHT_SERVICE_ACCESS_TOKEN: $(PLAYWRIGHT_SERVICE_ACCESS_TOKEN)
    PLAYWRIGHT_SERVICE_URL: $(PLAYWRIGHT_SERVICE_URL)
  inputs:
    targetType: "inline"
    script: "npx playwright test -c playwright.service.config.ts --workers=4"
    workingDirectory: path/to/playwright/folder # update accordingly

- task: PublishPipelineArtifact@1
  displayName: Upload Playwright report
  inputs:
    targetPath: path/to/playwright/folder/playwright-report/ # update accordingly
    artifact: "Playwright tests"
    publishLocation: "pipeline"
